// Code generated by mockery v2.20.2. DO NOT EDIT.

package main

import (
	context "context"
	sync "sync"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutorInterface is an autogenerated mock type for the ExecutorInterface type
type MockExecutorInterface struct {
	mock.Mock
}

// execute provides a mock function with given fields: ctx, wg
func (_m *MockExecutorInterface) Execute(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

type mockConstructorTestingTNewMockExecutorInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockExecutorInterface creates a new instance of MockExecutorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockExecutorInterface(t mockConstructorTestingTNewMockExecutorInterface) *MockExecutorInterface {
	mock := &MockExecutorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
